Edit DNSRecord in place when updating
Instead of replacing it with new one since some records
must have unique host and replcaing them using POST
request may end up with error:
```
error: failed to make http request: POST "https://api.cloudflare.com/client/v4/zones/***/dns_records": 400 Bad Request {"result":null,"success":false,"errors":[{"code":81053,"message":"An A, AAAA, or CNAME record with that host already exists. For more details, refer to \u003chttps://developers.cloudflare.com/dns/manage-dns-records/troubleshooting/records-with-same-name/\u003e."}],"messages":[]}
```